const CONSTANTES = {
  //SINIESTROS
  SINIESTROS_LISTA_OBTENER: 'SINIESTROS_LISTA_OBTENER',
  SINIESTROS_LISTA_RECIBE: 'SINIESTROS_LISTA_RECIBE',

  SINIESTROS_DETALLE_OBTENER: 'SINIESTROS_DETALLE_OBTENER',
  SINIESTROS_DETALLE_RECIBE: 'SINIESTROS_DETALLE_RECIBE',

  SINIESTROS_CREAR: 'SINIESTROS_CREAR',
  SINIESTROS_CREADO: 'SINIESTROS_CREADO',

  SINIESTROS_ACTUALIZAR: 'SINIESTROS_ACTUALIZAR',
  SINIESTROS_ACTUALIZADO: 'SINIESTROS_ACTUALIZADO',

  // --------------------------------------------------------------------------
  AUTH_LOGIN: 'LOGIN',
  AUTH_LOGIN_EXITOSO: 'LOGIN_EXITOSO',
  AUTH_LOGIN_ERROR: 'LOGIN_ERROR',

  LIMPIAR_ESTADO: 'LIMPIAR_ESTADO',
  LIMPIAR_ESTADO_DESMONTAR: 'LIMPIAR_ESTADO_DESMONTAR',

  API_ERROR_RESPUESTA: 'API_ERROR_RESPUESTA',
  API_SOLICITUD: 'API_SOLICITUD',

  // --------------------------------------------------------------------------
  ESTABLERCER_SESION: 'ESTABLERCER_SESION',
  ESTABLERCER_TOKEN_EXPO: 'ESTABLERCER_TOKEN_EXPO',
  ESTABLERCER_SESION_ID: 'ESTABLERCER_SESION_ID',
  CERRAR_SESION: 'CERRAR_SESION',

  AUTH_CERRAR_SESION: "AUTH_CERRAR_SESION",
  AUTH_SESION_CERRADA: "AUTH_SESION_CERRADA",

  // --------------------------------------------------------------------------
  STORAGE_SET_ITEM: "STORAGE_SET_ITEM",
  STORAGE_DELETE_ITEM: "STORAGE_DELETE_ITEM",
  STORAGE_CLEAR: "STORAGE_CLEAR"

};

export default CONSTANTES;
